server:
  port: 8847
    
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
 
logging:
  level:
    org: 
      hibernate:
        SQL: DEBUG

swagger:
  application:
    description: HCL HACKATHON DEMO
    version: 1.0
  
spring:
  application:
    name: hcl-hackathon-demo
  jpa:
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hcl-group
      auto-offset-reset: earliest

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: root

springdoc:
  swagger-ui:
    path: /doc/swagger-ui-custom.html
